extends: default

rules:
  line-length: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: true
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1

ignore: |
  .github/design-system.yml
